# Generated by Django 3.2.4 on 2021-07-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_listings_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='garages',
            field=models.IntegerField(default=1),
        ),
    ]
