# Generated by Django 3.2.4 on 2021-07-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_garages'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='floors',
            field=models.IntegerField(default=1),
        ),
    ]
