# Generated by Django 3.2.4 on 2021-08-02 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_name', models.CharField(max_length=50, null=True)),
                ('listing_id', models.IntegerField(null=True)),
                ('client_name', models.CharField(max_length=40, null=True)),
                ('client_email', models.CharField(max_length=50, null=True)),
                ('contact_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
