# Generated by Django 3.2.4 on 2021-08-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
